-- AoTv3 tracked table: command_settings
-- Generated by save.py on 2026-06-01 18:56:27
-- PK columns: command

REPLACE INTO `command_settings` (`command`, `access`, `aliases`) VALUES
('choosespell', 0, ''),
('resetspells', 100, ''),
('rollspell', 0, '');
