-- AoTv3 tracked table: command_settings
-- Generated by save.py on 2026-06-07 20:43:29
-- PK columns: command

REPLACE INTO `command_settings` (`command`, `access`, `aliases`) VALUES
('aotrebirth', 100, ''),
('choosespell', 0, ''),
('resetspells', 100, ''),
('rollspell', 0, '');
