-- AoTv3 tracked table: tradeskill_recipe
-- Generated by save.py on 2026-06-07 20:45:33
-- PK columns: id

REPLACE INTO `tradeskill_recipe` (`id`, `name`, `tradeskill`, `skillneeded`, `trivial`, `nofail`, `replace_container`, `notes`, `must_learn`, `learned_by_item_id`, `quest`, `enabled`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES
(27792, 'Crysta\'s Fufilled Order', 75, 0, 0, 1, 1, 'Halloween2018', 48, 0, 0, 1, -1, -1, 'Deez_halloween', NULL);
