-- AoTv3 tracked table: spawn_events
-- Generated by save.py on 2026-05-29 23:31:55
-- PK columns: id

REPLACE INTO `spawn_events` (`id`, `zone`, `cond_id`, `name`, `period`, `next_minute`, `next_hour`, `next_day`, `next_month`, `next_year`, `enabled`, `action`, `argument`, `strict`) VALUES
(48, 'qeynos', 2, 'Enable Day', 1440, 0, 7, 11, 4, 3998, 1, 0, 1, 0),
(49, 'qeynos', 2, 'Disable Day', 1440, 0, 21, 11, 4, 3998, 1, 0, 0, 0),
(50, 'qeynos', 1, 'Enable Night', 1440, 0, 21, 11, 4, 3998, 1, 0, 1, 0),
(51, 'qeynos', 1, 'Disable Night', 1440, 0, 7, 11, 4, 3998, 1, 0, 0, 0),
(56, 'overthere', 2, 'Enable Day', 1440, 0, 1, 12, 4, 3998, 1, 0, 1, 0),
(57, 'overthere', 2, 'Disable Day', 1440, 0, 21, 11, 4, 3998, 1, 0, 0, 0),
(58, 'overthere', 1, 'Enable Night', 1440, 0, 21, 11, 4, 3998, 1, 0, 1, 0),
(59, 'overthere', 1, 'Disable Night', 1440, 0, 7, 11, 4, 3998, 1, 0, 0, 0),
(64, 'natimbi', 1, 'SpawnCBQ', 1440, 0, 1, 12, 4, 3998, 1, 0, 1, 0),
(65, 'natimbi', 1, 'DespawnCBQ', 1440, 0, 3, 11, 4, 3998, 1, 0, 0, 0),
(74, 'erudnext', 2, 'Enable Day', 1440, 0, 7, 11, 4, 3998, 1, 0, 1, 0),
(75, 'erudnext', 2, 'Disable Day', 1440, 0, 21, 11, 4, 3998, 1, 0, 0, 0),
(76, 'erudnext', 1, 'Enable Night', 1440, 0, 21, 11, 4, 3998, 1, 0, 1, 0),
(77, 'erudnext', 1, 'Disable Night', 1440, 0, 7, 11, 4, 3998, 1, 0, 0, 0);
