-- AoTv3 tracked table: rule_values
-- Generated by save.py on 2026-06-07 20:44:57
-- PK columns: ruleset_id, rule_name

REPLACE INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`) VALUES
(1, 'AoT:DamageCapBaseDelayPct', '100', 'Base damage cap as a percent of weapon delay (100 = 100% of delay)'),
(1, 'AoT:DamageCapLevelPctPerLevel', '10', 'Additional cap percent of weapon delay added per character level (10 = +10% per level)'),
(1, 'AoT:DamageCapTwoHandBonusPct', '80', 'Additional percent bonus to the damage cap for two-handed weapons (80 = +80%, so 180% of 1H cap)'),
(1, 'AoT:MaxProcsPerTick', '6', 'Max total procs (weapon + spell + defensive combined) that can fire per 6-second tick; increased by SPA 531'),
(1, 'AoT:MeleeHasteCap', '100', 'Maximum melee haste bonus as a percent above base speed (100 = hard cap at double speed, i.e. GetHaste()=200)'),
(1, 'AoT:MemorizeDelayMs', '3000', 'Milliseconds a player must sit still after clicking a gem slot before the spell is memorized'),
(1, 'AoT:MitAcDR', '0.4000000059605', 'AC coefficient in the mitigation roll denominator. Higher = more DR on stacking AC; also raises the deflect threshold'),
(1, 'AoT:MitFloorAcCoeff', '1.2500000000000', 'AC coefficient in the mitigation floor formula: mit/(coeff*mit + scalar*off). Asymptote = 1/coeff (default 80% max floor)'),
(1, 'AoT:MitOffScalar', '2.0000000000000', 'Offense multiplier in the mitigation roll denominator. Higher = offense dominates more; also raises the deflect threshold'),
(1, 'AoT:SpellIdClientMaxID', '65535', 'Highest spell ID the RoF2 client tolerates; IDs above this crash the client'),
(1, 'AoT:SpellIdIndexBits', '8', 'Width in bits of the spell-index field (0-255 per tier)'),
(1, 'AoT:SpellIdIndexShift', '0', 'Bit offset of the spell-index field in the packed AoT spell ID'),
(1, 'AoT:SpellIdMasteryBits', '3', 'Width in bits of the mastery field (000=Apprentice; scroll upgrades increment this)'),
(1, 'AoT:SpellIdMasteryShift', '13', 'Bit offset of the mastery field in the packed AoT spell ID'),
(1, 'AoT:SpellIdNPCTierValue', '31', 'Stored tier bits value reserved for NPC-only spells (Tier 32)'),
(1, 'AoT:SpellIdTierBits', '5', 'Width in bits of the tier field (stored value = tier-1; stored 31 = NPC-only Tier 32)'),
(1, 'AoT:SpellIdTierShift', '8', 'Bit offset of the tier field in the packed AoT spell ID'),
(1, 'AoT:SpellRollOptions', '3', 'Number of spell options presented when rolling; increased by SPA 532'),
(1, 'Character:BlueModifier', '70', 'The experience obtained for blue con mobs is multiplied by value/100'),
(1, 'Character:GreenModifier', '20', 'The experience obtained for green con mobs is multiplied by value/100'),
(1, 'Character:LightBlueModifier', '35', 'The experience obtained for light-blue con mobs is multiplied by value/100'),
(1, 'Character:RedModifier', '325', 'The experience obtained for red con mobs is multiplied by value/100'),
(1, 'Character:WhiteModifier', '100', 'The experience obtained for white con mobs is multiplied by value/100'),
(1, 'Character:YellowModifier', '175', 'The experience obtained for yellow con mobs is multiplied by value/100'),
(1, 'Mercs:MaxMercSlots', '6', 'Maximum number of mercenary slots per character (max = MAXMERCS)'),
(1, 'Spells:NoFizzle', 'false', 'When enabled all spells always succeed their fizzle check — no fizzle chance.'),
(10, 'Character:RedModifier', '325', 'The experience obtained for red con mobs is multiplied by value/100'),
(10, 'Character:YellowModifier', '175', 'The experience obtained for yellow con mobs is multiplied by value/100');
