-- AoTv3 tracked table: rule_values
-- Generated by save.py on 2026-06-01 18:57:48
-- PK columns: ruleset_id, rule_name

REPLACE INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`) VALUES
(1, 'AoT:DamageCapBaseDelayPct', '100', 'Base damage cap as a percent of weapon delay (100 = 100% of delay)'),
(1, 'AoT:DamageCapLevelPctPerLevel', '10', 'Additional cap percent of weapon delay added per character level (10 = +10% per level)'),
(1, 'AoT:DamageCapTwoHandBonusPct', '80', 'Additional percent bonus to the damage cap for two-handed weapons (80 = +80%, so 180% of 1H cap)'),
(1, 'AoT:MaxProcsPerTick', '6', 'Max total procs (weapon + spell + defensive combined) that can fire per 6-second tick; increased by SPA 531'),
(1, 'AoT:SpellIdClientMaxID', '65535', 'Highest spell ID the RoF2 client tolerates; IDs above this crash the client'),
(1, 'AoT:SpellIdIndexBits', '8', 'Width in bits of the spell-index field (0-255 per tier)'),
(1, 'AoT:SpellIdIndexShift', '0', 'Bit offset of the spell-index field in the packed AoT spell ID'),
(1, 'AoT:SpellIdMasteryBits', '3', 'Width in bits of the mastery field (000=Apprentice; scroll upgrades increment this)'),
(1, 'AoT:SpellIdMasteryShift', '13', 'Bit offset of the mastery field in the packed AoT spell ID'),
(1, 'AoT:SpellIdNPCTierValue', '31', 'Stored tier bits value reserved for NPC-only spells (Tier 32)'),
(1, 'AoT:SpellIdTierBits', '5', 'Width in bits of the tier field (stored value = tier-1; stored 31 = NPC-only Tier 32)'),
(1, 'AoT:SpellIdTierShift', '8', 'Bit offset of the tier field in the packed AoT spell ID'),
(1, 'AoT:SpellRollOptions', '3', 'Number of spell options presented when rolling; increased by SPA 532'),
(1, 'Mercs:MaxMercSlots', '6', 'Maximum number of mercenary slots per character (max = MAXMERCS)'),
(1, 'Spells:NoFizzle', 'false', 'When enabled all spells always succeed their fizzle check — no fizzle chance.');
