-- AoTv3 tracked table: lootdrop_entries
-- Generated by save.py on 2026-06-07 20:44:47
-- PK columns: lootdrop_id, item_id

REPLACE INTO `lootdrop_entries` (`lootdrop_id`, `item_id`, `item_charges`, `equip_item`, `chance`, `disabled_chance`, `trivial_min_level`, `trivial_max_level`, `multiplier`, `npc_min_level`, `npc_max_level`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES
(991100, 990100, 1, 0, 2.0, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL),
(991101, 990101, 1, 0, 2.0, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL),
(991102, 990102, 1, 0, 2.0, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL),
(991103, 990103, 1, 0, 2.0, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL),
(991104, 990104, 1, 0, 2.0, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL),
(991105, 990105, 1, 0, 2.0, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL),
(991106, 990106, 1, 0, 2.0, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL);
