-- AoTv3 tracked table: spawngroup
-- Generated by save.py on 2026-05-29 03:40:29
-- PK columns: id

REPLACE INTO `spawngroup` (`id`, `name`, `spawn_limit`, `dist`, `max_x`, `min_x`, `max_y`, `min_y`, `delay`, `mindelay`, `despawn`, `despawn_timer`, `wp_spawns`) VALUES
(3290001, 'draniksscar_302093_recruiter', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 45000, 15000, 0, 100, 0),
(3290002, 'draniksscar_302097_epicquest', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 45000, 15000, 0, 100, 0),
(3290003, 'draniksscar_998038_guardwatch', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 45000, 15000, 0, 100, 0);
