#!/usr/bin/env python3
"""
save.py - Export AoT content changes from peq (live) vs peq_ref (baseline).
Generates REPLACE INTO for added/modified rows, DELETE for removed rows.
Run via: make save
"""

import os
import sys
import subprocess
from datetime import datetime

import configparser

import pymysql
import pymysql.cursors

DB_HOST = '127.0.0.1'
DB_PORT = 3306
DB_USER = 'peq'
DB_PASS = 'peqpass'
DB_LIVE = 'peq'
DB_REF  = 'peq_ref'

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT   = os.path.dirname(SCRIPT_DIR)
PK_CFG_PATH = os.path.join(SCRIPT_DIR, 'pk_config.ini')


def connect(db):
    return pymysql.connect(
        host=DB_HOST, port=DB_PORT,
        user=DB_USER, password=DB_PASS,
        database=db, charset='utf8mb4',
        cursorclass=pymysql.cursors.DictCursor
    )


def load_pk_config():
    cfg = configparser.ConfigParser()
    if os.path.exists(PK_CFG_PATH):
        cfg.read(PK_CFG_PATH)
    return cfg


def resolve_pks(cursor, table, pk_cfg):
    """
    Returns (pk_cols, source) where source is 'config' or 'schema'.
    Config wins over schema when both exist.
    Raises ValueError with actionable message if neither has PKs.
    """
    if pk_cfg.has_section(table) and pk_cfg.has_option(table, 'pk'):
        cols = [c.strip() for c in pk_cfg.get(table, 'pk').split(',')]
        return cols, 'config'

    cursor.execute("""
        SELECT COLUMN_NAME
        FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = %s
          AND TABLE_NAME = %s
          AND CONSTRAINT_NAME = 'PRIMARY'
        ORDER BY ORDINAL_POSITION
    """, (DB_LIVE, table))
    cols = [row['COLUMN_NAME'] for row in cursor.fetchall()]

    if cols:
        return cols, 'schema'

    raise ValueError(
        f"no PKs found in schema or pk_config.ini.\n"
        f"    Add to database/pk_config.ini:\n"
        f"    [{table}]\n"
        f"    pk = <col>[, <col2>, ...]"
    )


def get_columns(cursor, db, table):
    cursor.execute("""
        SELECT COLUMN_NAME
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = %s
          AND TABLE_NAME = %s
        ORDER BY ORDINAL_POSITION
    """, (db, table))
    return [row['COLUMN_NAME'] for row in cursor.fetchall()]


def fetch_all(cursor, table):
    cursor.execute(f"SELECT * FROM `{table}`")
    return cursor.fetchall()


def escape_val(val):
    if val is None:
        return 'NULL'
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, bytes):
        return f"0x{val.hex()}"
    s = str(val)
    s = s.replace('\\', '\\\\')
    s = s.replace("'", "\\'")
    s = s.replace('\0', '\\0')
    s = s.replace('\n', '\\n')
    s = s.replace('\r', '\\r')
    return f"'{s}'"


def pk_tuple(row, pk_cols):
    return tuple(row[col] for col in pk_cols)


def generate_sql(table, pk_cols, columns, replaced, deleted):
    lines = [
        f"-- AoTv3 tracked table: {table}",
        f"-- Generated by save.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"-- PK columns: {', '.join(pk_cols)}",
        "",
    ]

    if replaced:
        col_list = ', '.join(f'`{c}`' for c in columns)
        val_rows = []
        for row in sorted(replaced, key=lambda r: pk_tuple(r, pk_cols)):
            vals = ', '.join(escape_val(row[col]) for col in columns)
            val_rows.append(f"({vals})")
        lines.append(f"REPLACE INTO `{table}` ({col_list}) VALUES")
        lines.append(',\n'.join(val_rows) + ';')
        lines.append("")

    if deleted:
        sorted_del = sorted(deleted)
        if len(pk_cols) == 1:
            pk_col = pk_cols[0]
            in_list = ', '.join(escape_val(t[0]) for t in sorted_del)
            lines.append(f"DELETE FROM `{table}` WHERE `{pk_col}` IN ({in_list});")
        else:
            col_list = ', '.join(f'`{c}`' for c in pk_cols)
            in_list = ', '.join(
                '(' + ', '.join(escape_val(v) for v in t) + ')'
                for t in sorted_del
            )
            lines.append(f"DELETE FROM `{table}` WHERE ({col_list}) IN ({in_list});")
        lines.append("")

    return '\n'.join(lines)


def discover_tables():
    tables = []
    for entry in os.scandir(SCRIPT_DIR):
        if entry.is_dir() and not entry.name.startswith('.'):
            tables.append(entry.name)
    return sorted(tables)


def save_table(table, conn_live, conn_ref, pk_cfg):
    cur_live = conn_live.cursor()
    cur_ref  = conn_ref.cursor() if conn_ref else None

    pk_cols, source = resolve_pks(cur_live, table, pk_cfg)
    tag = '[config]' if source == 'config' else '[schema]'
    print(f"  {tag} {table}: pk={', '.join(pk_cols)}")

    columns = get_columns(cur_live, DB_LIVE, table)

    live_rows = {pk_tuple(r, pk_cols): r for r in fetch_all(cur_live, table)}

    ref_rows = {}
    if cur_ref:
        try:
            ref_rows = {pk_tuple(r, pk_cols): r for r in fetch_all(cur_ref, table)}
        except Exception:
            pass  # table may not exist in ref yet

    replaced = []
    deleted  = []

    for pk, row in live_rows.items():
        if pk not in ref_rows or row != ref_rows[pk]:
            replaced.append(row)

    for pk in ref_rows:
        if pk not in live_rows:
            deleted.append(pk)

    if not replaced and not deleted:
        print(f"  {table}: no changes")
        return False

    sql = generate_sql(table, pk_cols, columns, replaced, deleted)
    out_path = os.path.join(SCRIPT_DIR, table, f"{table}.sql")
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(sql)

    print(f"  {table}: {len(replaced)} upserted, {len(deleted)} deleted -> {table}/{table}.sql")
    return True


def git_run(args):
    result = subprocess.run(['git', '-C', REPO_ROOT] + args, capture_output=True, text=True)
    if result.stdout.strip():
        print(f"    {result.stdout.strip()}")
    if result.returncode != 0 and result.stderr.strip():
        print(f"    [git] {result.stderr.strip()}")
    return result.returncode == 0


def main():
    tables = discover_tables()
    if not tables:
        print("No tracked tables found in database/")
        sys.exit(1)

    pk_cfg = load_pk_config()

    print(f"Connecting to {DB_LIVE}...")
    try:
        conn_live = connect(DB_LIVE)
    except Exception as e:
        print(f"Cannot connect to {DB_LIVE}: {e}")
        sys.exit(1)

    conn_ref = None
    try:
        conn_ref = connect(DB_REF)
        print(f"Connected to {DB_REF} (diffing against baseline).")
    except Exception:
        print(f"[WARN] {DB_REF} not found — treating all rows as new (bootstrap mode).")
        print("       Run 'make load' to establish a proper baseline.")

    print(f"\nSaving {len(tables)} table(s): {', '.join(tables)}\n")

    changed = []
    for table in tables:
        try:
            if save_table(table, conn_live, conn_ref, pk_cfg):
                changed.append(table)
        except Exception as e:
            print(f"  [ERROR] {table}: {e}")

    conn_live.close()
    if conn_ref:
        conn_ref.close()

    if not changed:
        print("\nNo changes detected — nothing to commit.")
        return

    print(f"\n{len(changed)} table(s) changed. Committing to git...")

    git_run(['pull', '--rebase'])
    git_run(['add', 'database/'])

    summary = f"save: {len(changed)} table(s): {', '.join(changed)}"
    if not git_run(['commit', '-m', summary]):
        print("  Nothing to commit (already up to date).")
        return

    if not git_run(['push']):
        print("  [WARN] Push failed. You may need to pull --rebase and push manually.")
        return

    print("Done.")


if __name__ == '__main__':
    main()
