-- AoTv3 tracked table: spawnentry
-- Generated by save.py on 2026-06-01 18:58:06
-- PK columns: spawngroupID, npcID

REPLACE INTO `spawnentry` (`spawngroupID`, `npcID`, `chance`, `condition_value_filter`, `min_time`, `max_time`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES
(17010, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17011, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17012, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17013, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17014, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17015, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17016, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17017, 335016, 100, 1, 0, 0, -1, -1, NULL, NULL),
(17019, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17020, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17021, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17022, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(17023, 335016, 34, 1, 0, 0, -1, -1, NULL, NULL),
(43560, 335016, 90, 1, 0, 0, -1, -1, NULL, NULL),
(43563, 335016, 90, 1, 0, 0, -1, -1, NULL, NULL),
(43587, 335020, 100, 1, 0, 0, -1, -1, NULL, NULL),
(3290001, 302093, 100, 1, 0, 0, -1, -1, NULL, NULL),
(3290002, 302097, 100, 1, 0, 0, -1, -1, NULL, NULL),
(3290003, 998038, 100, 1, 0, 0, -1, -1, NULL, NULL);

DELETE FROM `spawnentry` WHERE (`spawngroupID`, `npcID`) IN ((17010, 335043), (17011, 335043), (17012, 335043), (17013, 335043), (17014, 335043), (17015, 335043), (17016, 335043), (17017, 335043), (17019, 335043), (17020, 335043), (17021, 335043), (17022, 335043), (17023, 335043), (43560, 335042), (43563, 335043), (43587, 335018));
