-- AoTv3 tracked table: loottable
-- Generated by save.py on 2026-05-29 23:31:40
-- PK columns: id

REPLACE INTO `loottable` (`id`, `name`, `mincash`, `maxcash`, `avgcoin`, `done`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES
(12381, 'Deezi_Biato', 0, 0, 0, 1, -1, -1, NULL, NULL);
