-- AoTv3 tracked table: lootdrop
-- Generated by save.py on 2026-06-07 20:44:16
-- PK columns: id

REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES
(20316, '20067_Deezi_Biato_Misc', -1, -1, NULL, NULL),
(991100, 'epic2_draniksscar_fragment', -1, -1, NULL, NULL),
(991101, 'epic2_causeway_fragment', -1, -1, NULL, NULL),
(991102, 'epic2_bloodfields_fragment', -1, -1, NULL, NULL),
(991103, 'epic2_dranik_fragment', -1, -1, NULL, NULL),
(991104, 'epic2_harbingers_fragment', -1, -1, NULL, NULL),
(991105, 'epic2_wallofslaughter_fragment', -1, -1, NULL, NULL),
(991106, 'epic2_riftseekers_fragment', -1, -1, NULL, NULL);
